# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventLite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='eventsInterested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventLite.Event'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='ticketsPurchased',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventLite.Ticket'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='eventsHosting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventLite.Event'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='bio',
            field=models.CharField(blank=True, default=b'', max_length=420, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='buyer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventLite.Buyer'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=b'icons'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='seller',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventLite.Seller'),
        ),
    ]
