# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventLite', '0002_remove_userdetail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='eventsInterested',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='EventLite.Event'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='ticketsPurchased',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='EventLite.Ticket'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='eventsHosting',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='EventLite.Event'),
        ),
    ]
